openapi: '3.0.3'
info:
  title: User Management
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /users/register:
    post:
      summary: Register a new user
      operationId: registerUser
      tags: ["users"]
      requestBody: 
        content: 
          application/json: 
            schema: 
              $ref: "./src/components/schemas/RegisterUserRequest.yaml"
        required: true
      responses:
        "201":
          description: Registered the new user successfully
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/RegisterUserResponse.yaml"
        "400":
          description: Invalid username/password/email
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "409":
          description: Username/email already exists
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        default:
          description: unexpected error
  /users/login:
    post:
      summary: Authenticate user and issue tokens
      operationId: authenticateUser
      tags: ["users"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./src/components/schemas/LoginUserRequest.yaml"
        required: true
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/LoginUserResponse.yaml"
        "400":
          description: Malformed request or missing credentials
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "401":
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        default:
          description: unexpected error
  /users/refresh-token:
    post:
      summary: Issue new access token using refresh token
      operationId: refreshToken
      tags: ["users"]
      description: Supports httpOnly cookie (browser clients) and request body (mobile clients)
      parameters:
        - name: refresh_token
          in: cookie
          description: Refresh token stored in cookie
          required: false
          schema:
            type: string
      requestBody:
        description: Refresh token sent thru the request body
        content:
          application/json:
            schema:
              $ref: "./src/components/schemas/LogoutUserRequest.yaml"
        required: false
      responses:
        "200":
          description: Token successfully refreshed
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/RefreshTokenResponse.yaml"
        "400":
          description: Malformed request or missing token
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "401":
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "429":
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        default:
          description: unexpected error
  /users/logout:
    post:
      summary: Invalidate the refresh token
      operationId: logoutUser
      tags: ["users"]
      description: Supports httpOnly cookie (browser clients) and request body (mobile clients)
      parameters:
        - name: refresh_token
          in: cookie
          description: Refresh token stored in cookie
          required: false
          schema:
            type: string
      requestBody:
        description: Refresh token sent thru the request body
        content:
          application/json:
            schema:
              $ref: "./src/components/schemas/LogoutUserRequest.yaml"
        required: false
      responses:
        "204":
          description: Logged out successfully, no content
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./src/components/schemas/ErrorResponse.yaml"
        default:
          description: unexpected error      
